Map<String, String> france = {
  // drawer
  "Update Residence" :   "Mettre à jour la résidence",
  "bookingReq": "Demande de réservation",
  "myResindence": "Mes residences",
  "income": "Revenu",
  "setting": "Paramètre",
  "support": "Soutien",
  "aboutUs": "À propos de nous",
  "logOut": "Se déconnecter",
  "Booking Details": "Les détails de réservation",
  "You sure want to Residence": "Vous voulez certainement résider",
  "Yes": "Oui",
  "No": "Non",
  "Edit": "Modifier",
  "Delete": "Supprimer",
  "History": " Histoire",
  "You sure want to delete message?": "Voulez-vous vraiment supprimer le message ?",
  "Edit Profile": "Editer le profil",
  "Profile": "Profil",
  "Save": "Sauvegarder",
  "Confirm" : "Confirmez",


  "residenceDetails": "Détails de la résidence",

  "No Data Found": "Aucune donnée disponible",
  //onboard

  "subWelcome": "Votre solution de réservation complète.",
    'Get Started': "Commencez",
  "Forget Password?": "Mot de passe oublié?",
  "Forget Password": "Mot de passe oublié",
  "Booking List": "Liste de réservation",
  "Are you sure you want to log out?":"Êtes-vous sûr de vouloir vous déconnecter?",
  "Search Residence":"Rechercher une résidence",

  //auth

  "welcome": "Bienvenue chez Résid Plus",
  "email": "Email",
  "password": "Mot de passe",
  "signIn": "Se connecter",
  "doYouHaveAc": "Pas de compte? ",
  "signUp?" : "Inscrivez-vous",
  "Please enter a valid email .": "Veuillez entrer un Email valide .",
  "Forgot Password": "Mot de passe oublié",
  "OTP":"Bureau du Procureur",
  "Successful":"Réussie",
  "OTP Send To your Email":"OTP Envoyer à votre e-mail",
  "Verify":"Vérifier",
  "Error": "Erreur",
  "Reset Password":"Réinitialiser le mot de passe",
  "Your password must have 8-10 characters.":"Votre mot de passe doit comporter 8 à 10 caractères.",
  "New Password":"Nouveau mot de passe",
  "Please enter your password": "S'il vous plait entrez votre mot de passe",
  "Password doesn't match":"Le mot de passe ne correspond pas",
  "Confirm Your Password":"Confirmer votre mot de passe",
  "Please use uppercase,lowercase,spacial character and number":"Veuillez utiliser des majuscules, des minuscules, des caractères spéciaux et des chiffres.",
  "Please use 8 character long password":"Veuillez utiliser un mot de passe de 8 caractères",
  "Reset":"Réinitialisez",
  "Name Not Be Empty":"Le nom ne doit pas être vide",
  "Name is to long":"Le nom ne doit pas être vide",
  "Please enter a valid date.":"Veuillez entrer une date valide.",
  "Date not more then 2 digits":"Date ne dépassant pas 2 chiffres",
  "Please enter a valid Month.":"Veuillez entrer un mois valide.",
  "Month date not more then 2 digits":"Date du mois ne dépassant pas 2 chiffres",
  "Please enter a valid Year.":"Veuillez entrer une année valide.",
  "Year not more then 4 digits":"Année pas plus de 4 chiffres",
  "Year not less than 4 digits":"Année pas moins de 4 chiffres",
  "Phone number not less than 10 digits":"Numéro de téléphone d'au moins 10 chiffres",
  "Phone number not more then 14 digits":"Numéro de téléphone ne dépassant pas 14 chiffres",
  "Address Not Be Empty":"L'adresse ne doit pas être vide",
  "Please use uppercase, lowercase, special character, and number":"Please use uppercase, lowercase, special character, and number",
  "Verify Email":"Vérifier les courriels",
  "User logged in successfully": "Connecté avec succès",
  "Internet Error":"Erreur Internet",
  "Internal Server Error":"Erreur interne du serveur",
  "Phone Number" : "Numéro de téléphone",
  "Enter Number" : "Entrer un nombre",
  "Invalid email and password" : "Email et mot de passe invalides",
  "Email verify successful" : "Vérification de l'e-mail réussie",


  "name": "Nom",
  "dob": "Date de naissance",
  "phoneNum": "Numéro de téléphone",
  "confirmPassword": "Confirmez le mot de passe",
  "Phone number not less then 10 digits":"Numéro de téléphone composé d'au moins 10 chiffresa",
  "signUp": "S'inscrire",
  "Password Reset Successful" : "Réinitialisation du mot de passe réussie",
  "Enter your email" : 'Entrez votre email',
  "Enter your Password" : 'Entrez votre  mot de pass',
  "Please enter a valid email.": "Entrez un email valide",
  "Please enter your valid email": "Veuillez entrer votre email valide",

  "Password Not Be Empty": "Le mot de passe ne doit pas être vide",
  "Password Should Be 8-character": "Le mot de passe doit être composé de 8 caractères",

  "Please enter the OTP code.": "Entrez votre code OTP",
  "Please enter your email address to reset your password." : "Entrez votre adresse email pour renitialiser votre mot de pass",
   "Did not get the OTP?" : "Pas recu le OTP",
  "Resend OTP" : "Renvoyez L'OTP",
  "Enter your name" : "Entrez votre Nom",
  "Password does not match!" : "Le mot de passe ne correspond pas!",

  "*Must enter your date of birth" : "*Doit entrer votre date de naissance",
  "*Must enter your valid number" : "*Vous devez entrer votre numéro valide",

  "Enter your address": "Entrez votre adresse",
  "Enter your number" :   "Entrez votre numéro",



  "or": "Ou",
  // home
  "newResidence": "Ajouter une nouvelle résidence",
  "searchResidence": "Rechercher une résidence",
  "All": "Toute",
  "New": "Nouvelle",
  "Popular": "Populaire",

  "Hotel": "Hôtel",
  "Residence": "Résidence",
  "PersonalHouse": "Maison personnelle",

  "seeAll": "Voir tout",
  "Personal House":"Maison personnelle",

  "booking ": "Reservation",
  "host": "Gérant",
  "user": "Utilisateur",
  "userInformation": "Infos Utilisateurs",
  "hostInformation": "Infos Géran",
  "userList ": "Liste d’utilisateurs",
  "search": " Recherche",
  "contact": "Contacts",
  "address": "Adresse",
  "bookingCompleted": "Reservation complétée",
  "residenceInformation": "Informations de la résidence",
  "active": "Active",
  "reserved": "Réserver",
  "Favorite":"Préférée",


  // Add Residence
  "addResidence": "Ajouter une résidence",
  "uploadPhoto": 'télécharger 5 photos',
  "residencName": "Nom de la résidence",
  "ownerInformation": "Information du propriétaire",
  "capacityPerson": " Capacité/personne",
  "beds": "Chambres",
  "bath": "Thermes",
  "city": "ville",
  "rentHr": "Louer/heure",
  "aboutResidence": "À propos de l résidence",
  "municipality": "Municipalité",
  "quartar": "Quart",
  "setAmount": "Fixer le montant de résidence",
  "setCategory": "Définir la catégorie de résidence",
  "setAminities": "Définir les commodités de la résidence",
  "about": "À propos",
  "add": "Ajouter",

  // animities
  "wifi":"wifi",
  "air-conditioner":"climatiseur",
  "pets":"pets",
  "kitchen":"cuisine",
  "tv":"tv",
  "internet":"internet",
  "washing-machine": "Machine à laver",
  "dryer":"dryer",
  "refrigerator": "réfrigérateur",
  "heating":"heating",
  "parking": "parking",

  "Enter how many beds" : "Nombres de Lits",
  "Enter how many baths" : "Nombres de douches",
  "Enter residence address" : "Entrez l'adresse de la residence",
  "Enter city name" : "Entrez le nom de la ville",
  "Enter municipality name": "Entrez la commune",
  "Enter quartier": "Entrez le quartier",

  "Enter Residence Name" : "Entrez le nom de la résidence",
  "Enter person number" : "Entrez le numéro de personne",

  "Enter about residence": "Entrez à propos de la résidence",
  "Enter name" : "Entrez le nom",
  "About yourself" : "A propos de toi",

  "ownerName": "Nom du Gérant",
  "Field can't be empty":"Le champ ne peut pas être vide",

  //setting
  "Languages": "Langues",
  "settings": "Paramètres",
  "changePassword": "Changer le mot de passe",
  "termsServices": "Conditions de services",
  "Privacy Policy": "Politique de confidentialité",
  "FAQ": "FAQ",
  "Language Change": "Changement de langue",

  "Current Password": "Mot de passe actuel",
  "Confirm New Password": "Confirmer le nouveau mot de passe",
  "continue": "Continuer",
  "OTP Verify Successful" : "Vérification OTP réussie",

  "Enter password" : "Entrer le mot de passe",
  "Enter new Password" : "Entrez un nouveau mot de passe",
  "Enter confirm Password" : "Entrez confirmer le mot de passe",
  "No reservation data found" : "Aucune donnée de réservation trouvée",
  "No history data found" : "Aucune donnée d'historique trouvée",
  //income

  "Daily Income": "Revenu quotidien",
  "Weekly Income": "Revenu hebdomadaire",
  "Monthly Income": "Revenu mensuel",
  "Total Income": "Revenu total",
  'logOutAlert':"Vous voulez vraiment vous déconnecter ?",

  //notificationout
  "Notification" : "Notification",
  "No notification available":"Aucune notification disponible",


  //No Internet
  "NO Internet Connection" : "Pas de connexion Internet",
  "PLEASE CONNECT TO THE INTERNET" : "VEUILLEZ VOUS CONNECTER À INTERNET",

  "Language Changed Successfully": "La langue a changé avec succès",


  //Message Screen
  "Type message" : "Tapez le message",
  "Back" : "Dos",

  "Booking Information" : "Informations de réservation",
  "User Name" : "Nom d'utilisateur",
  "User Contact" : "Contact utilisateur",
  "Total Person" : "Personne totale",
  "Start Date" : "Date de début",
  "End Date" : "Date de fin",

  "Booking Successfully" : "Réservation réussie",
  "Successfully profile updated" : "Profil mis à jour avec succès",
  "Somethings went wrong" : "Quelque chose s'est mal passé",
  'Reserve' : "Réserve",
  "Residence Details" :"Détails de la résidence",
  '/hr' : '/heure',
  "/5-hr" : "/5-heures",
  '/day' : '/jour',
  "City" : "Ville",
  "Municipality" : "Municipalité",
  "Quarter" : "Quart",
  'Check In' : 'Enregistrement',
  'Check Out' : 'Vérifier',
  'Residence Amenities' : "Commodités de la résidence",
  "About this residence" : "A propos de cette résidence",
  "Top Reviews" : "Meilleures critiques",

  " night" : " nuit",
  "Alert" : "Alerte",
  "Please Enter Date Time" : "Veuillez entrer la date et l'heure",
  "Select Date" : "Sélectionner une date",
  "Residence Reservation" : "Réservation de résidence",
  'Total time' : 'Temps total',
  "Number of Guests" : "Nombre d'invités",
  "Enter guest number" : "Entrez le numéro d'invité",
  "Please Enter Number of Guests" : "Veuillez entrer le nombre d'invités",
  "Half Amount" : "La moitié du montant",
  "Cancel" : "Annuler",
  "Adults Only" : "Seulment les adultes",
  "adults-only" : "seulment les adultes",
  "Including Child" : "Y compris l'enfant",
  "including-child" : "y compris-enfant",
  'Total Amount' : 'Montant total',
  "Host Information" : "Informations sur l'hôte",

  "Please Wait For Host Approval" : "Veuillez attendre l'approbation de l'hôte",
  "Total Amount includes Service charge and Transaction Fee": "Le montant total comprend les frais de service et les frais de transaction",
  "You have Paid Half the Amount, Please Pay in Full Amount then you can checkout." : "Vous avez payé la moitié du montant, veuillez payer le montant total, puis vous pourrez passer à la caisse."


};
